pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.9-eclipse-temurin-21-alpine' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:26-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
} 
